### ISSUE TITLE
Can you provide a pre-trained model

### ISSUE THREAD

**Issue by mstd-jie** [shannanyinxiang/SPTS#1]
thanks

**Comment by shannanyinxiang** [comment]
A pre-trained model is available at [https://drive.google.com/file/d/1nI4KlHTbFxgVI8pNSGjbTRxS4OohgTq5/view?usp=sharing](url).

**Comment by shannanyinxiang** [comment]
A pre-trained model is available at [https://drive.google.com/file/d/1nI4KlHTbFxgVI8pNSGjbTRxS4OohgTq5/view?usp=sharing]().

**Comment by shannanyinxiang** [comment]
A pre-trained model is available at [link](https://drive.google.com/file/d/1nI4KlHTbFxgVI8pNSGjbTRxS4OohgTq5/view?usp=sharing).
