### ISSUE TITLE
Evaluation on Custom dataset

### ISSUE THREAD

**Issue by k-styles** [shannanyinxiang/SPTS#10]
Hi,
I am using your work in my project on a custom dataset for text spotting.
I had a doubt on the evaluation folder - I would like to use my custom dataset to train with this model, but I am not really aware on how should i setup the evaluation folder. It would be great if you could let me know about how you have prepared the evaluation files for icdar and totaltext datasets.

**Comment by shannanyinxiang** [comment]
Taking TotalText for example, the `gt_totaltext` folder contains `.txt` annotation files, each for a single test sample. The filename of the `.txt` annotation file is the `image_id` (provided in `.json` annotations) of the corresponding test sample.

The `.txt` annotation file contains multiple lines, each of which corresponds to a text instance. The format of one line is as follows.
```
x_1,y_1,x_2,y_2,...,x_n,y_n,####content
```
where the `x_1,y_1,x_2,y_2,...,x_n,y_n` are the coordinates of the polygon, and the `content` is the recognition annotation.
