### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by babble2** [shannanyinxiang/SPTS#11]
hi, thanks for your great work! could you provide pre-trained model?

**Comment by shannanyinxiang** [comment]
A pre-trained model can be found here #1.

**Comment by babble2** [comment]
你好：
&nbsp; &nbsp; &nbsp;想请问一下SPTSv2这个工作什么时候开源呢








青春，活力，有梦想
 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Apr 12, 2023 10:00 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [shannanyinxiang/SPTS] pre-trained model (Issue #11)

&nbsp;



 
Closed #11 as completed.

**Comment by shannanyinxiang** [comment]
> 你好： &nbsp; &nbsp; &nbsp;想请问一下SPTSv2这个工作什么时候开源呢 青春，活力，有梦想 &nbsp; &nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: &nbsp;Wed, Apr 12, 2023 10:00 AM To: ***@***.***&gt;; Cc: ***@***.***&gt;; ***@***.***&gt;; Subject: &nbsp;Re: [shannanyinxiang/SPTS] pre-trained model (Issue #11) &nbsp; Closed #11 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

预计一个月内。
