### ISSUE TITLE
pretrain time

### ISSUE THREAD

**Issue by babble2** [shannanyinxiang/SPTS#13]
How long did it take you to pretrain the existing A100，and how big batch of A100, thx!

**Comment by shannanyinxiang** [comment]
The pretraining using 10 A100s takes approximately 4 days with automatic mixed precision (torch.amp).
The total batch size is 40, i.e., the batch size of each A100 is 4.

**Comment by babble2** [comment]
Hello, now I have a problem, can you help me,&nbsp;I made some changes on your model and&nbsp;use the same configuration repeated experiments many times but get different results, how can solve it?
By the way，When you experiment with 10 A100s, “Batch” is set to 40？










 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sun, Jun 11, 2023 09:01 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [shannanyinxiang/SPTS] pretrain time (Issue #13)

&nbsp;



 
The pretraining using 10 A100s takes approximately 4 days with automatic mixed precision (torch.amp).
 The total batch size is 40, i.e., the batch size of each A100 is 4.
