### ISSUE TITLE
Help wanted about NPTS.

### ISSUE THREAD

**Issue by ZhengyaoFang** [shannanyinxiang/SPTS#14]
May I ask if you can provide an implementation code for NPTS? We would like to test it on some other datasets for research purpose. I guarantee any future work based on your code will reference your paper properly. Appreciate your help :)

**Comment by shannanyinxiang** [comment]
Thank you for your interest! 
I will update the code for NPTS this week.

**Comment by shannanyinxiang** [comment]
Try the code at the [NPTS](https://github.com/shannanyinxiang/SPTS/tree/npts) branch!
The training and inference codes are ready but the evaluation code requires further adaptation.
If you find any bugs, feel free to comment here or PR.

**Comment by ZhengyaoFang** [comment]
Thank you very much for your response! Also, may I ask if you could kindly disclose the checkpoints for NPTS? Thank you so much!

**Comment by shannanyinxiang** [comment]
The checkpoint for NPTS is stored in the company's server during my previous internship. I currently don't have a copy of it. Therefore, I'm sorry that I can't provide the checkpoint for NPTS.
