### ISSUE TITLE
How to generate the "rec" in annotation?

### ISSUE THREAD

**Issue by littlesheep111** [shannanyinxiang/SPTS#15]
Hi,

I want to use my own data to train, however, I don't know how to annotate the "rec". Anyone can help me?

In icdar2013 dataset, the annotation is like:
'rec': [52, 73, 82, 69, 68, 78, 69, 83, 83, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96], 'rec_string': 'Tiredness'.  I think that '52' is for 'T', '73' is for 'i', etc. However, I don't know the vocabulary exactly.

Thanks.

**Comment by littlesheep111** [comment]
I have solved this problem. However, I wonder how to get the 'bezier_pts'?

**Comment by shannanyinxiang** [comment]
The generation of 'bezier_pts' follows ABCNet.
This [repo](https://github.com/Yuliang-Liu/bezier_curve_text_spotting?tab=readme-ov-file#generated-results-download) provides the bezier-curve generation script.
