### ISSUE TITLE
Question regarding dataset ground truth text

### ISSUE THREAD

**Issue by rdyzakya** [shannanyinxiang/SPTS#2]
Hello, actually I haven't found any issue for the code, but I have a question regarding the dataset for training. While in the readme it said that we have to download the dataset and move it to the data folder in order to train it, but I don't find any ground truth for the text label there. Did I miss something from the explanation in the paper or something else?

Thanks

**Comment by rdyzakya** [comment]
Oh, I have found that the 'rec' key leads to the text label. This made me confuse since the vocabulary is written in the parser code (chars argument). Is there any way to use this code without creating bbox and bezier_pts? since the premise of the paper is to simplify the annotation process.

**Comment by shannanyinxiang** [comment]
Sorry for the late reply.

- Regarding the ground-truth text, as you have found, it can be obtained by combining the 'rec' key in .json files and the vocabulary (args.chars).

- Regarding the simplification of annotations, the key steps are:
  1. Delete the 'bbox'&'bezier_pts' keys from .json files. 
  2. Add a key (e.g., 'pt') that contains the coordinate of the single point into .json files. 
  3. Read the coordinate of the single point into target['pt'] in **TextSpottingDataset** (_dataset/text_spotting.py_).
  4. Delete the operations on target['bboxes'] and target['bezier_pts'] from _dataset/transforms.py_.
  5. Implement the transformations on target['pt'] in _dataset/transforms.py_.
  6. Modify the **SeqConstructor** (_dataset/collate_fn.py_) to directly get center_pts from target['pt'].
