### ISSUE TITLE
您好请问您如何解决无坐标学习后模型出现输出冗余的现象

### ISSUE THREAD

**Issue by Airwithcode** [shannanyinxiang/SPTS#5]
如一个字符输出多次，或者比如单词SPTS，输出SPT、PTS等冗余值，感谢您的回答

**Comment by shannanyinxiang** [comment]
可能是因为eos token出现过晚，可以尝试在训练过程中调大eos token的损失系数（在训练命令中增加--eos_loss_coef参数来设置eos token的损失系数）。

**Comment by yangxcccscsa** [comment]
> 如一个字符输出多次，或者比如单词SPTS，输出SPT、PTS等冗余值，感谢您的回答

您好，我是一名做文字检测识别的研究生，我可以加您微信问您一些问题吗？我的微信号：ZY18220759108
