### ISSUE TITLE
Annotation files for ICDAR15

### ISSUE THREAD

**Issue by k-styles** [shannanyinxiang/SPTS#9]
Hi, just starting out in this field, and amazing paper by the way!
I wanted to test this model on a custom dataset.
So I would like to know a bit about the rec field in your json annotations files. Could you please let me know how that kind of embedding is done in the literature?

**Comment by shannanyinxiang** [comment]
The rec field sequentially records the indices of the characters in a word.
The word content can be recovered using the indices in the rec field and the character list in args.chars.

**Comment by k-styles** [comment]
Thanks!
That clears it!
